apiVersion: v1
kind: BuildConfig
metadata:
  name: nuancier-build
  labels:
    environment: "nuancier"
spec:
  output:
    to:
      kind: ImageStreamTag
      name: nuancier:latest
  source:
    type: Git
    git:
      uri: https://github.com/jontrossbach/nuancier.git
      ref: nuancier_crc_openshift
      #{% if env == 'staging' %}
      #ref: "staging"
      #{% else %}
      #ref: "production"
      #{% endif %}
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: python:3.6
  triggers:
  - type: ConfigChange
  - type: ImageChange
  - type: "GitHub"
    github:
      secretReference:
        name: "gitsecret"
